Feature/db and auth
YRIDZE/Bicycle-delivery-service pull request #2
Opened 2021-08-20 14:49 UTC by YRIDZE

2021-08-23 15:19 UTC, Metadorius requested changes
The code seems to be good aside from minor issues. Usage of experimental generics may greately reduce the repetition of code though. Also since the PR is WIP should mark it as draft.

2021-08-23 15:19 UTC, Metadorius commented on pkg/handlers/order_handler.go
> +	r.Handle("/orderD/{id}", appH.userHandler.AuthMiddleware(http.HandlerFunc(h.Delete)))
As it seems RESTful API shouldn't contain CRUD names:

> URIs should not be used to indicate that a CRUD function is performed. URIs should be used to uniquely identify resources and not any action upon them. HTTP request methods should be used to indicate which CRUD function is performed.

from https://restfulapi.net/resource-naming/

2021-08-23 15:19 UTC, Metadorius commented on pkg/handlers/user_handler.go
> +	r.Handle("/userD", appH.userHandler.AuthMiddleware(http.HandlerFunc(h.Delete)))
Same thing with naming, also I am not sure if exposing an endpoint to look up user by email is a good practice from security standpoint.

2021-08-23 15:19 UTC, Metadorius commented on pkg/services/tokens_service.go
> +}
Seems like there should be an error returned instead of an empty string?

2021-08-23 15:19 UTC, Metadorius commented on pkg/models/db_repository/order_repository.go
> +	//}
```suggestion
```

2021-08-23 15:19 UTC, Metadorius commented on pkg/models/file_repository/user_repository.go
>  	return nil
```suggestion
	panic("implement me")
```

2021-08-29 13:41 UTC, VitaliaSmaglenko approved these changes

2021-09-02 16:00 UTC, merged